<?php

namespace BerqWP;

// autoload_psr4.php @generated by Composer
$vendorDir = \dirname(__DIR__);
$baseDir = \dirname($vendorDir);
return array('BerqWP\\GuzzleHttp\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'), 'BerqWP\\GuzzleHttp\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'), 'BerqWP\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'), 'BerqWP\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'), 'BerqWP\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'), 'BerqWP\\' => array($baseDir . '/src'));
